### ISSUE TITLE
x = self.encoder(x)[0]后channel数量不改变

### ISSUE THREAD

**Issue by yiqigo0215** [zdaiot/Kaggle-Steel-Defect-Detection#1]
x = torch.Tensor(1, 3, 256, 1600)
model_name = 'unet_resnet50'
class_net = ClassifyResNet(model_name, 4, encoder_weights=None)
output = class_net(x)
怎么一直报Given groups=1, weight of size [512, 2048, 1, 1], expected input[1, 3, 1, 1] to have 2048 channels, but got 3 channels instead。
在ClassifyResNet中的forward中第一部已经先做x = self.encoder(x)[0]，这时候x不应该是2048channels吗，为什么打印x.size()的时候还是只有3channels
希望能得到您的解答

**Comment by zdaiot** [comment]
您好，可能是您库的版本和我的不一致，我在readme中更新了各个库的版本号，您安装特定版本的库之后再试试。

**Comment by yiqigo0215** [comment]
您好，方便问下，您是用列出的三个模型得到的平均结果吗，我用5折跑了这三个模型70epoches，dice都在0.67左右

**Comment by zdaiot** [comment]
不好意思，具体的我也忘了，您可以查看下 https://github.com/zdaiot/Kaggle-Steel-Defect-Detection/blob/master/experiments.md 这个文件，里面有一些记录
