### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by shiwei-913** [zdaiot/Kaggle-Steel-Defect-Detection#2]
I don’t understand the data set processing of this competition. After using the code to convert all the EncodedPixels of each picture into a mask matrix, what kind of file is stored? There seems to be no other description in the process. I hope to get you For the answer, thanks

**Comment by zdaiot** [comment]
Hello, I did not store these, see https://github.com/zdaiot/Kaggle-Steel-Defect-Detection/blob/master/datasets/steel_dataset.py#L67 for details

**Comment by shiwei-913** [comment]
> 您好，我没有存储这些，有关详细信息，请参见https://github.com/zdaiot/Kaggle-Steel-Defect-Detection/blob/master/datasets/steel_dataset.py#L67

I will study carefully, thank you for your reply！
